#### processing the other data from MappingPlants####

pacman::p_load(googlesheets4)

plant_traits <- read_sheet("https://docs.google.com/spreadsheets/d/1gAAk09YgYKcUidop3xwplKaXW3rQoOgUoF4EtZganAA/edit?gid=407247046#gid=407247046", sheet = 'clean_data')


colnames(points)

plant_traits <- points |> 
  select( CreationDa,
          Creator,
          EditDate,
          Editor,
          X_date,
          species,
          untitled_q,
          untitled_1,
          vegetation,
          field_8,
          field_13,
          start_time,
          end_time,
          vegetati_1,
          vegetati_2,
          vegetati_3,
          species_1,
          field_28_o,
          untitled_2,
          soil_moist,
          soil_temp_,
          soil_moi_1,
          soil_temp1,
          soil_moi_2,
          soil_tem_1,
          soil_moi_3,
          soil_tamp_,
          topographi,
          bryophyte_,
          field_47,
          lichen_bra,
          species_1_,
          species_11,
          species_2,
          taxon_2_he,
          taxon_2_br,
          taxon_3,
          taxon_3_he,
          taxon_3_br,
          taxon_4,
          taxon_4_he,
          taxon_4_br,
          taxon_5,
          taxon_5_he,
          taxon_5_br,
          taxon_6,
          taxon_6_he,
          taxon_6_br,
          taxon_7,
          taxon_7_he,
          taxon_7_br,
          taxon_8,
          taxon_8_he,
          taxon_8_br,
          taxon_9,
          taxon_9_he,
          taxon_9_br,
          taxon_10,
          taxon_10_h,
          taxon_10_b,
          taxon_11,
          taxon_11_h,
          taxon_11_b,
          taxon_12,
          taxon_12_h,
          taxon_12_b,
          taxon_13,
          taxon_13_h,
          taxon_14,
          taxon_14_h,
          taxon_14_b,
          taxon_15,
          taxon_15_h,
          taxon_15_b,
          taxon_16,
          taxon_16_h,
          taxon_16_b,
          taxon_17,
          taxon_17_h,
          taxon_17_b,
          taxon_18,
          taxon_18_h,
          other_note,)
